services:
  postgres:
    image: postgres:latest
    container_name: e2e_postgres
    environment:
      POSTGRES_DB: "bookbook_db_e2e"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"

  s3:
    image: minio/minio:latest
    container_name: e2e_s3
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
